'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource_PL
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBlib.Resource_PL", GetType(Resource_PL).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PL.
        '''</summary>
        Friend Shared ReadOnly Property _lang() As String
            Get
                Return ResourceManager.GetString("_lang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fragment nazwy:.
        '''</summary>
        Friend Shared ReadOnly Property msgEnterName() As String
            Get
                Return ResourceManager.GetString("msgEnterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tekst do szukania:.
        '''</summary>
        Friend Shared ReadOnly Property msgSearchReroute() As String
            Get
                Return ResourceManager.GetString("msgSearchReroute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tak.
        '''</summary>
        Friend Shared ReadOnly Property msgYes() As String
            Get
                Return ResourceManager.GetString("msgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To chyba nie jest liczba.
        '''</summary>
        Friend Shared ReadOnly Property resBadFloat() As String
            Get
                Return ResourceManager.GetString("resBadFloat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zmiany na liście przystanków:.
        '''</summary>
        Friend Shared ReadOnly Property resChangesInStopList() As String
            Get
                Return ResourceManager.GetString("resChangesInStopList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wszystkie.
        '''</summary>
        Friend Shared ReadOnly Property resDlgCancel() As String
            Get
                Return ResourceManager.GetString("resDlgCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Szukaj.
        '''</summary>
        Friend Shared ReadOnly Property resDlgContinue() As String
            Get
                Return ResourceManager.GetString("resDlgContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błąd: nie rozumiem danych z TTSS.
        '''</summary>
        Friend Shared ReadOnly Property resErrorBadTTSSstops() As String
            Get
                Return ResourceManager.GetString("resErrorBadTTSSstops", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błąd: wystąpił błąd w komunikacji sieciowej..
        '''</summary>
        Friend Shared ReadOnly Property resErrorGetHttp() As String
            Get
                Return ResourceManager.GetString("resErrorGetHttp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błąd: nie mam dostępu do lokalizacji.
        '''</summary>
        Friend Shared ReadOnly Property resErrorGettingPos() As String
            Get
                Return ResourceManager.GetString("resErrorGettingPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zbyt długie oczekiwanie na sieć.
        '''</summary>
        Friend Shared ReadOnly Property resErrorHttpTimeout() As String
            Get
                Return ResourceManager.GetString("resErrorHttpTimeout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błąd: nazwa jest za krótka.
        '''</summary>
        Friend Shared ReadOnly Property resErrorNazwaZaKrotka() As String
            Get
                Return ResourceManager.GetString("resErrorNazwaZaKrotka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brak dostępu do usługi lokalizacji (sprawdź w systemie uprawnienia dla aplikacji) - używam danych testowych.
        '''</summary>
        Friend Shared ReadOnly Property resErrorNoGPSAllowed() As String
            Get
                Return ResourceManager.GetString("resErrorNoGPSAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błąd: bez sieci nie właduję danych!.
        '''</summary>
        Friend Shared ReadOnly Property resErrorNoNetwork() As String
            Get
                Return ResourceManager.GetString("resErrorNoNetwork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wybierz współrzędne w obrębie Krakowa....
        '''</summary>
        Friend Shared ReadOnly Property resErrorPozaKrakowem() As String
            Get
                Return ResourceManager.GetString("resErrorPozaKrakowem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błąd konwersji XML?.
        '''</summary>
        Friend Shared ReadOnly Property resErrorXMLload() As String
            Get
                Return ResourceManager.GetString("resErrorXMLload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sieć tram w.
        '''</summary>
        Friend Shared ReadOnly Property resHistoriaTitle() As String
            Get
                Return ResourceManager.GetString("resHistoriaTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zaimportowałem poprzednią listę miejsc.
        '''</summary>
        Friend Shared ReadOnly Property resImportedOldFav() As String
            Get
                Return ResourceManager.GetString("resImportedOldFav", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do najbliższego przystanku masz  ###. .
        '''</summary>
        Friend Shared ReadOnly Property resNearestStop() As String
            Get
                Return ResourceManager.GetString("resNearestStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dodaj.
        '''</summary>
        Friend Shared ReadOnly Property resSettAdd() As String
            Get
                Return ResourceManager.GetString("resSettAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usuń.
        '''</summary>
        Friend Shared ReadOnly Property resSettDel() As String
            Get
                Return ResourceManager.GetString("resSettDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dokładność lokalizacji.
        '''</summary>
        Friend Shared ReadOnly Property resSettGPSPrec_Header() As String
            Get
                Return ResourceManager.GetString("resSettGPSPrec.Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [wprowadź].
        '''</summary>
        Friend Shared ReadOnly Property resSettPosItemEnter() As String
            Get
                Return ResourceManager.GetString("resSettPosItemEnter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [GPS].
        '''</summary>
        Friend Shared ReadOnly Property resSettPosItemGPS() As String
            Get
                Return ResourceManager.GetString("resSettPosItemGPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Przystanki linii.
        '''</summary>
        Friend Shared ReadOnly Property resTrasa() As String
            Get
                Return ResourceManager.GetString("resTrasa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- użyj wyszukiwania.
        '''</summary>
        Friend Shared ReadOnly Property resUseSearch() As String
            Get
                Return ResourceManager.GetString("resUseSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie ma kursów....
        '''</summary>
        Friend Shared ReadOnly Property resZeroKursow() As String
            Get
                Return ResourceManager.GetString("resZeroKursow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (więcej info).
        '''</summary>
        Friend Shared ReadOnly Property resZmianyLink() As String
            Get
                Return ResourceManager.GetString("resZmianyLink", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
